//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databasedb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dlgocEntities : DbContext
    {
        public dlgocEntities()
            : base("name=dlgocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOANMONTH> LOANMONTHs { get; set; }
    
        public virtual ObjectResult<getCIFInfo_Result> getCIFInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCIFInfo_Result>("getCIFInfo");
        }
    
        public virtual ObjectResult<GetFullCIFInfo_Result> GetFullCIFInfo(Nullable<decimal> cif)
        {
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFullCIFInfo_Result>("GetFullCIFInfo", cifParameter);
        }
    }
}
