//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databasedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOANMONTH
    {
        public string ACNAME { get; set; }
        public decimal CIFNO { get; set; }
        public decimal ACCTNO { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> GROUP { get; set; }
        public string BRN { get; set; }
        public string ODIND { get; set; }
        public Nullable<decimal> TERM { get; set; }
        public string TMCODE { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<System.DateTime> ORGDT6 { get; set; }
        public Nullable<System.DateTime> MATDT6 { get; set; }
        public Nullable<System.DateTime> ORGMD6 { get; set; }
        public Nullable<System.DateTime> NSPDT6 { get; set; }
        public Nullable<System.DateTime> NSIPD6 { get; set; }
        public Nullable<decimal> EXTLTD { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string CURTYP { get; set; }
        public Nullable<decimal> MTDREL { get; set; }
        public Nullable<decimal> MTDPRN { get; set; }
        public Nullable<decimal> YTDREL { get; set; }
        public Nullable<decimal> YTDPRN { get; set; }
        public Nullable<decimal> AMTREL { get; set; }
        public Nullable<decimal> LTDPRN { get; set; }
        public Nullable<System.DateTime> NIPDT6 { get; set; }
        public Nullable<System.DateTime> ODIND6 { get; set; }
        public Nullable<decimal> CBAL { get; set; }
        public Nullable<decimal> ACCINT { get; set; }
        public Nullable<decimal> PENINT { get; set; }
        public string PURCOD { get; set; }
        public string CLASS { get; set; }
        public Nullable<decimal> DEPTCD { get; set; }
        public Nullable<decimal> INTLTD { get; set; }
        public Nullable<decimal> YTDINT { get; set; }
        public Nullable<decimal> MTDINT { get; set; }
        public decimal YTDLC { get; set; }
        public decimal MTDLC { get; set; }
        public Nullable<decimal> EXTYTD { get; set; }
        public Nullable<decimal> FRELD6 { get; set; }
        public Nullable<System.DateTime> NPDT6 { get; set; }
        public Nullable<decimal> AFAPLY { get; set; }
        public Nullable<System.DateTime> POFFD6 { get; set; }
        public Nullable<System.DateTime> LMDate { get; set; }
        public string BRANCH { get; set; }
        public Nullable<System.DateTime> Datadate { get; set; }
        public Nullable<decimal> BILINT { get; set; }
        public Nullable<decimal> PMTAMT { get; set; }
        public Nullable<decimal> BILPRN { get; set; }
        public string LNMUID { get; set; }
        public Nullable<decimal> ACCIN2 { get; set; }
        public string PARTID { get; set; }
        public Nullable<decimal> PDIEM { get; set; }
        public string AACARC { get; set; }
        public string MCLNID { get; set; }
        public Nullable<decimal> PREVDT { get; set; }
        public Nullable<System.DateTime> PREVD6 { get; set; }
        public Nullable<decimal> PRTERM { get; set; }
        public string PRCODE { get; set; }
        public Nullable<decimal> FCODE { get; set; }
        public Nullable<decimal> COMACC { get; set; }
        public Nullable<System.DateTime> RREVD6 { get; set; }
        public Nullable<decimal> RRTERM { get; set; }
        public string RRCODE { get; set; }
        public Nullable<decimal> BILLC { get; set; }
        public Nullable<decimal> BILLCO { get; set; }
        public Nullable<decimal> IPFREQ { get; set; }
        public Nullable<decimal> LCTYPE { get; set; }
        public Nullable<decimal> OPFREQ { get; set; }
        public string LRSTOD { get; set; }
        public Nullable<decimal> AACLMT { get; set; }
        public Nullable<decimal> AAAPNO { get; set; }
        public Nullable<decimal> AFSEQ { get; set; }
        public string AFFCDE { get; set; }
        public string AFCPNO { get; set; }
        public string AFCUR { get; set; }
        public Nullable<decimal> AFFAMT { get; set; }
        public Nullable<decimal> AFLIMT { get; set; }
        public string AACURR { get; set; }
        public Nullable<decimal> AAM1H { get; set; }
        public string DEPTCODE { get; set; }
    }
}
