//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDMAST_DATE
    {
        public Nullable<System.DateTime> DATADATE { get; set; }
        public decimal BRANCH { get; set; }
        public string ACNAME { get; set; }
        public decimal CIFNO { get; set; }
        public decimal ACCTNO { get; set; }
        public string SCCODE { get; set; }
        public decimal DDGRUP { get; set; }
        public decimal RATE { get; set; }
        public string DDMUID { get; set; }
        public string DDCTYP { get; set; }
        public Nullable<System.DateTime> DATOP6 { get; set; }
        public Nullable<System.DateTime> DLA6 { get; set; }
        public decimal CBAL { get; set; }
        public decimal ACCRUE { get; set; }
        public decimal HOLD { get; set; }
        public string PGDID { get; set; }
        public string STATUS { get; set; }
        public string PVAR1 { get; set; }
        public decimal PVAR { get; set; }
        public decimal AMTDRC { get; set; }
        public decimal AMTCR { get; set; }
        public string CLASS { get; set; }
        public decimal DMPRDC { get; set; }
        public string DDCDEC { get; set; }
        public string ACTYPE { get; set; }
        public Nullable<System.DateTime> LMDATE { get; set; }
        public string ODPROT { get; set; }
        public Nullable<decimal> ODDLIM { get; set; }
        public Nullable<decimal> OTRATE { get; set; }
        public Nullable<System.DateTime> OTDTE { get; set; }
        public Nullable<System.DateTime> OTEXP { get; set; }
        public Nullable<System.DateTime> OTDTE2 { get; set; }
        public Nullable<System.DateTime> OTEXP2 { get; set; }
        public Nullable<decimal> ODINT { get; set; }
        public Nullable<decimal> ODEXSS { get; set; }
        public Nullable<decimal> PFLOOR { get; set; }
        public Nullable<decimal> PCEIL { get; set; }
        public Nullable<decimal> ORATE { get; set; }
        public string DEPTCODE { get; set; }
        public Nullable<decimal> OTRTN { get; set; }
        public string OTPVR1 { get; set; }
        public Nullable<decimal> OTPVAR { get; set; }
        public Nullable<decimal> OTCEIL { get; set; }
        public Nullable<decimal> OTFLOR { get; set; }
        public Nullable<decimal> ODUNAC { get; set; }
    }
}
