//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dlgocEntities : DbContext
    {
        public dlgocEntities()
            : base("name=dlgocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DDDHIS_DATE> DDDHIS_DATE { get; set; }
        public virtual DbSet<DDMAST_DATE> DDMAST_DATE { get; set; }
        public virtual DbSet<tb_checkdulieu> tb_checkdulieu { get; set; }
        public virtual DbSet<tb_loaiKH> tb_loaiKH { get; set; }
        public virtual DbSet<X1PCMS> X1PCMS { get; set; }
        public virtual DbSet<GLHIST> GLHISTs { get; set; }
        public virtual DbSet<LNDHIS_DATE> LNDHIS_DATE { get; set; }
        public virtual DbSet<GLHIST_ERP> GLHIST_ERP { get; set; }
        public virtual DbSet<GLMAST_ERP> GLMAST_ERP { get; set; }
        public virtual DbSet<GLMAST> GLMASTs { get; set; }
    
        [DbFunction("dlgocEntities", "GetMonthList")]
        public virtual IQueryable<GetMonthList_Result> GetMonthList(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetMonthList_Result>("[dlgocEntities].[GetMonthList](@StartDate, @EndDate)", startDateParameter, endDateParameter);
        }
    
        [DbFunction("dlgocEntities", "ListDates")]
        public virtual IQueryable<ListDates_Result> ListDates(string startDate, string endDate)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ListDates_Result>("[dlgocEntities].[ListDates](@StartDate, @EndDate)", startDateParameter, endDateParameter);
        }
    
        [DbFunction("dlgocEntities", "LsgdGL")]
        public virtual IQueryable<LsgdGL_Result> LsgdGL(string tkgl, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<int> branch, string tRCTYP)
        {
            var tkglParameter = tkgl != null ?
                new ObjectParameter("tkgl", tkgl) :
                new ObjectParameter("tkgl", typeof(string));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(int));
    
            var tRCTYPParameter = tRCTYP != null ?
                new ObjectParameter("TRCTYP", tRCTYP) :
                new ObjectParameter("TRCTYP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LsgdGL_Result>("[dlgocEntities].[LsgdGL](@tkgl, @ngaybd, @ngaykt, @branch, @TRCTYP)", tkglParameter, ngaybdParameter, ngayktParameter, branchParameter, tRCTYPParameter);
        }
    
        public virtual ObjectResult<binhquantiengui_Result> binhquantiengui(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, string loaikh)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var loaikhParameter = loaikh != null ?
                new ObjectParameter("loaikh", loaikh) :
                new ObjectParameter("loaikh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<binhquantiengui_Result>("binhquantiengui", ngaybdParameter, ngayktParameter, loaikhParameter);
        }
    
        public virtual int bqtienguiThang(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string listcif)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var listcifParameter = listcif != null ?
                new ObjectParameter("listcif", listcif) :
                new ObjectParameter("listcif", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bqtienguiThang", startDateParameter, endDateParameter, listcifParameter);
        }
    
        public virtual int check_ngay_dl(string tablename, Nullable<System.DateTime> ngaydlbd, Nullable<System.DateTime> ngaydlkt)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            var ngaydlbdParameter = ngaydlbd.HasValue ?
                new ObjectParameter("ngaydlbd", ngaydlbd) :
                new ObjectParameter("ngaydlbd", typeof(System.DateTime));
    
            var ngaydlktParameter = ngaydlkt.HasValue ?
                new ObjectParameter("ngaydlkt", ngaydlkt) :
                new ObjectParameter("ngaydlkt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("check_ngay_dl", tablenameParameter, ngaydlbdParameter, ngaydlktParameter);
        }
    
        public virtual ObjectResult<DoanhSoTientheoCif_Result> DoanhSoTientheoCif(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<int> cif)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoanhSoTientheoCif_Result>("DoanhSoTientheoCif", ngaybdParameter, ngayktParameter, cifParameter);
        }
    
        public virtual ObjectResult<getCIFInfo_Result> getCIFInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCIFInfo_Result>("getCIFInfo");
        }
    
        public virtual int laytygia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("laytygia");
        }
    
        public virtual ObjectResult<laytygia_ngay_Result> laytygia_ngay(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<laytygia_ngay_Result>("laytygia_ngay", ngayParameter);
        }
    
        public virtual ObjectResult<laytygia_tungay_denngay_Result> laytygia_tungay_denngay(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<laytygia_tungay_denngay_Result>("laytygia_tungay_denngay", ngaybdParameter, ngayktParameter);
        }
    
        public virtual ObjectResult<LichSuGiaoDichTheoCIF_Result> LichSuGiaoDichTheoCIF(Nullable<decimal> cifno, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, string loai)
        {
            var cifnoParameter = cifno.HasValue ?
                new ObjectParameter("cifno", cifno) :
                new ObjectParameter("cifno", typeof(decimal));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichSuGiaoDichTheoCIF_Result>("LichSuGiaoDichTheoCIF", cifnoParameter, ngaybdParameter, ngayktParameter, loaiParameter);
        }
    
        public virtual ObjectResult<LichSuGiaoDichTheoTK_Result> LichSuGiaoDichTheoTK(Nullable<decimal> tRACCT, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, string loai)
        {
            var tRACCTParameter = tRACCT.HasValue ?
                new ObjectParameter("TRACCT", tRACCT) :
                new ObjectParameter("TRACCT", typeof(decimal));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichSuGiaoDichTheoTK_Result>("LichSuGiaoDichTheoTK", tRACCTParameter, ngaybdParameter, ngayktParameter, loaiParameter);
        }
    
        public virtual ObjectResult<Lsgd_GL_Result> Lsgd_GL(string tkgl, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<int> branch, string tRCTYP)
        {
            var tkglParameter = tkgl != null ?
                new ObjectParameter("tkgl", tkgl) :
                new ObjectParameter("tkgl", typeof(string));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(int));
    
            var tRCTYPParameter = tRCTYP != null ?
                new ObjectParameter("TRCTYP", tRCTYP) :
                new ObjectParameter("TRCTYP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lsgd_GL_Result>("Lsgd_GL", tkglParameter, ngaybdParameter, ngayktParameter, branchParameter, tRCTYPParameter);
        }
    
        public virtual int LsTienGui(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<decimal> cif)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LsTienGui", ngaybdParameter, ngayktParameter, cifParameter);
        }
    
        public virtual ObjectResult<SaoKeCif_Result> SaoKeCif(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<int> cif)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaoKeCif_Result>("SaoKeCif", ngaybdParameter, ngayktParameter, cifParameter);
        }
    
        public virtual ObjectResult<SoDuKHTienGui_Result> SoDuKHTienGui(Nullable<System.DateTime> ngaybc, string loaikh)
        {
            var ngaybcParameter = ngaybc.HasValue ?
                new ObjectParameter("ngaybc", ngaybc) :
                new ObjectParameter("ngaybc", typeof(System.DateTime));
    
            var loaikhParameter = loaikh != null ?
                new ObjectParameter("loaikh", loaikh) :
                new ObjectParameter("loaikh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SoDuKHTienGui_Result>("SoDuKHTienGui", ngaybcParameter, loaikhParameter);
        }
    
        public virtual ObjectResult<SoDuKHTienGui_ChiTiet_Result> SoDuKHTienGui_ChiTiet(Nullable<System.DateTime> ngaybc, Nullable<decimal> cif)
        {
            var ngaybcParameter = ngaybc.HasValue ?
                new ObjectParameter("ngaybc", ngaybc) :
                new ObjectParameter("ngaybc", typeof(System.DateTime));
    
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SoDuKHTienGui_ChiTiet_Result>("SoDuKHTienGui_ChiTiet", ngaybcParameter, cifParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SoDuTKGL(string tkgl, Nullable<System.DateTime> ngay, Nullable<int> branch, string tien)
        {
            var tkglParameter = tkgl != null ?
                new ObjectParameter("tkgl", tkgl) :
                new ObjectParameter("tkgl", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(int));
    
            var tienParameter = tien != null ?
                new ObjectParameter("tien", tien) :
                new ObjectParameter("tien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SoDuTKGL", tkglParameter, ngayParameter, branchParameter, tienParameter);
        }
    
        public virtual ObjectResult<ThuNoThuLai_Result> ThuNoThuLai(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<int> cif)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThuNoThuLai_Result>("ThuNoThuLai", ngaybdParameter, ngayktParameter, cifParameter);
        }
    
        public virtual ObjectResult<PhieuDoiChieu_Result> PhieuDoiChieu(Nullable<decimal> cifno, Nullable<System.DateTime> currentDate, Nullable<int> bds, string loc)
        {
            var cifnoParameter = cifno.HasValue ?
                new ObjectParameter("cifno", cifno) :
                new ObjectParameter("cifno", typeof(decimal));
    
            var currentDateParameter = currentDate.HasValue ?
                new ObjectParameter("CurrentDate", currentDate) :
                new ObjectParameter("CurrentDate", typeof(System.DateTime));
    
            var bdsParameter = bds.HasValue ?
                new ObjectParameter("bds", bds) :
                new ObjectParameter("bds", typeof(int));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhieuDoiChieu_Result>("PhieuDoiChieu", cifnoParameter, currentDateParameter, bdsParameter, locParameter);
        }
    
        public virtual ObjectResult<SoDuTaiTD_Result> SoDuTaiTD(Nullable<System.DateTime> ngaybc)
        {
            var ngaybcParameter = ngaybc.HasValue ?
                new ObjectParameter("ngaybc", ngaybc) :
                new ObjectParameter("ngaybc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SoDuTaiTD_Result>("SoDuTaiTD", ngaybcParameter);
        }
    
        public virtual ObjectResult<TinhPhiTheoCif_Result> TinhPhiTheoCif(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<int> cif)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TinhPhiTheoCif_Result>("TinhPhiTheoCif", ngaybdParameter, ngayktParameter, cifParameter);
        }
    
        public virtual ObjectResult<TonQuy_Result> TonQuy(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TonQuy_Result>("TonQuy", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<SaoKeTienVay_Result> SaoKeTienVay(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<decimal> tkvay)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var tkvayParameter = tkvay.HasValue ?
                new ObjectParameter("tkvay", tkvay) :
                new ObjectParameter("tkvay", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaoKeTienVay_Result>("SaoKeTienVay", startDateParameter, endDateParameter, tkvayParameter);
        }
    
        public virtual ObjectResult<laytygiangay_Result> laytygiangay(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<laytygiangay_Result>("laytygiangay", ngayParameter);
        }
    
        public virtual ObjectResult<TraGoc_Result> TraGoc(Nullable<System.DateTime> ngaydl, Nullable<System.DateTime> ngaytragoctungay, Nullable<System.DateTime> ngaytragocdenngay)
        {
            var ngaydlParameter = ngaydl.HasValue ?
                new ObjectParameter("ngaydl", ngaydl) :
                new ObjectParameter("ngaydl", typeof(System.DateTime));
    
            var ngaytragoctungayParameter = ngaytragoctungay.HasValue ?
                new ObjectParameter("ngaytragoctungay", ngaytragoctungay) :
                new ObjectParameter("ngaytragoctungay", typeof(System.DateTime));
    
            var ngaytragocdenngayParameter = ngaytragocdenngay.HasValue ?
                new ObjectParameter("ngaytragocdenngay", ngaytragocdenngay) :
                new ObjectParameter("ngaytragocdenngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraGoc_Result>("TraGoc", ngaydlParameter, ngaytragoctungayParameter, ngaytragocdenngayParameter);
        }
    
        public virtual ObjectResult<TraLai_Result> TraLai(Nullable<System.DateTime> ngaydl, Nullable<System.DateTime> ngaytragoctungay, Nullable<System.DateTime> ngaytragocdenngay)
        {
            var ngaydlParameter = ngaydl.HasValue ?
                new ObjectParameter("ngaydl", ngaydl) :
                new ObjectParameter("ngaydl", typeof(System.DateTime));
    
            var ngaytragoctungayParameter = ngaytragoctungay.HasValue ?
                new ObjectParameter("ngaytragoctungay", ngaytragoctungay) :
                new ObjectParameter("ngaytragoctungay", typeof(System.DateTime));
    
            var ngaytragocdenngayParameter = ngaytragocdenngay.HasValue ?
                new ObjectParameter("ngaytragocdenngay", ngaytragocdenngay) :
                new ObjectParameter("ngaytragocdenngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraLai_Result>("TraLai", ngaydlParameter, ngaytragoctungayParameter, ngaytragocdenngayParameter);
        }
    
        public virtual ObjectResult<phiPos_Result> phiPos(Nullable<System.DateTime> ngaybc, Nullable<System.DateTime> ngaykt)
        {
            var ngaybcParameter = ngaybc.HasValue ?
                new ObjectParameter("ngaybc", ngaybc) :
                new ObjectParameter("ngaybc", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phiPos_Result>("phiPos", ngaybcParameter, ngayktParameter);
        }
    
        public virtual ObjectResult<MuaBanNgoaiTe_Result> MuaBanNgoaiTe(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MuaBanNgoaiTe_Result>("MuaBanNgoaiTe", ngayParameter);
        }
    
        public virtual ObjectResult<tracuulsgl_Result> tracuulsgl(Nullable<decimal> tkgl, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<int> branch, string tRCTYP)
        {
            var tkglParameter = tkgl.HasValue ?
                new ObjectParameter("tkgl", tkgl) :
                new ObjectParameter("tkgl", typeof(decimal));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(int));
    
            var tRCTYPParameter = tRCTYP != null ?
                new ObjectParameter("TRCTYP", tRCTYP) :
                new ObjectParameter("TRCTYP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tracuulsgl_Result>("tracuulsgl", tkglParameter, ngaybdParameter, ngayktParameter, branchParameter, tRCTYPParameter);
        }
    
        public virtual ObjectResult<TraCuuGLERP_Result> TraCuuGLERP(Nullable<decimal> tkgl, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt)
        {
            var tkglParameter = tkgl.HasValue ?
                new ObjectParameter("tkgl", tkgl) :
                new ObjectParameter("tkgl", typeof(decimal));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraCuuGLERP_Result>("TraCuuGLERP", tkglParameter, ngaybdParameter, ngayktParameter);
        }
    
        public virtual int BcDuno_HuyDong(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BcDuno_HuyDong", ngayParameter);
        }
    
        public virtual int BcDuno_HuyDong_tangGiam(Nullable<System.DateTime> ngay, ObjectParameter retr)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BcDuno_HuyDong_tangGiam", ngayParameter, retr);
        }
    
        public virtual int BcTuan_HDV_Vay(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaytruoc)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaytruocParameter = ngaytruoc.HasValue ?
                new ObjectParameter("ngaytruoc", ngaytruoc) :
                new ObjectParameter("ngaytruoc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BcTuan_HDV_Vay", ngaydauParameter, ngaytruocParameter);
        }
    
        public virtual int BcTuan_HDV_Vay_chiTiet(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaytruoc)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaytruocParameter = ngaytruoc.HasValue ?
                new ObjectParameter("ngaytruoc", ngaytruoc) :
                new ObjectParameter("ngaytruoc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BcTuan_HDV_Vay_chiTiet", ngaydauParameter, ngaytruocParameter);
        }
    
        public virtual ObjectResult<GetFullCIFInfo_Result> GetFullCIFInfo(Nullable<decimal> cif)
        {
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFullCIFInfo_Result>("GetFullCIFInfo", cifParameter);
        }
    
        public virtual int GiaoDichBienDongHDV(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaytruoc, Nullable<decimal> limit)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaytruocParameter = ngaytruoc.HasValue ?
                new ObjectParameter("ngaytruoc", ngaytruoc) :
                new ObjectParameter("ngaytruoc", typeof(System.DateTime));
    
            var limitParameter = limit.HasValue ?
                new ObjectParameter("Limit", limit) :
                new ObjectParameter("Limit", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaoDichBienDongHDV", ngaydauParameter, ngaytruocParameter, limitParameter);
        }
    
        public virtual int GiaoDichBienDongTienVay(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaytruoc, Nullable<decimal> limit)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaytruocParameter = ngaytruoc.HasValue ?
                new ObjectParameter("ngaytruoc", ngaytruoc) :
                new ObjectParameter("ngaytruoc", typeof(System.DateTime));
    
            var limitParameter = limit.HasValue ?
                new ObjectParameter("Limit", limit) :
                new ObjectParameter("Limit", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaoDichBienDongTienVay", ngaydauParameter, ngaytruocParameter, limitParameter);
        }
    
        public virtual ObjectResult<thauchi_mpa_Result> thauchi_mpa(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thauchi_mpa_Result>("thauchi_mpa", ngayParameter);
        }
    
        public virtual ObjectResult<saokethauchi_Result> saokethauchi(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, Nullable<decimal> tk)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var tkParameter = tk.HasValue ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saokethauchi_Result>("saokethauchi", ngaybdParameter, ngayktParameter, tkParameter);
        }
    
        public virtual ObjectResult<ThongBaoDuNo_Result> ThongBaoDuNo(Nullable<decimal> cif)
        {
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongBaoDuNo_Result>("ThongBaoDuNo", cifParameter);
        }
    
        public virtual ObjectResult<ThongBaoNoDenHan_Result> ThongBaoNoDenHan(Nullable<decimal> cif)
        {
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongBaoNoDenHan_Result>("ThongBaoNoDenHan", cifParameter);
        }
    
        public virtual ObjectResult<TinhThuLaiGocTheoCIF_Result> TinhThuLaiGocTheoCIF(Nullable<System.DateTime> dNgayLaiDen, Nullable<decimal> cifno)
        {
            var dNgayLaiDenParameter = dNgayLaiDen.HasValue ?
                new ObjectParameter("dNgayLaiDen", dNgayLaiDen) :
                new ObjectParameter("dNgayLaiDen", typeof(System.DateTime));
    
            var cifnoParameter = cifno.HasValue ?
                new ObjectParameter("cifno", cifno) :
                new ObjectParameter("cifno", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TinhThuLaiGocTheoCIF_Result>("TinhThuLaiGocTheoCIF", dNgayLaiDenParameter, cifnoParameter);
        }
    
        public virtual ObjectResult<TinhThuLaiTheoCIF_Result> TinhThuLaiTheoCIF(Nullable<System.DateTime> dNgayLaiDen, Nullable<decimal> cifno)
        {
            var dNgayLaiDenParameter = dNgayLaiDen.HasValue ?
                new ObjectParameter("dNgayLaiDen", dNgayLaiDen) :
                new ObjectParameter("dNgayLaiDen", typeof(System.DateTime));
    
            var cifnoParameter = cifno.HasValue ?
                new ObjectParameter("cifno", cifno) :
                new ObjectParameter("cifno", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TinhThuLaiTheoCIF_Result>("TinhThuLaiTheoCIF", dNgayLaiDenParameter, cifnoParameter);
        }
    
        public virtual ObjectResult<LayTKThanhToanTheoCIF_Result> LayTKThanhToanTheoCIF(Nullable<decimal> cif)
        {
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayTKThanhToanTheoCIF_Result>("LayTKThanhToanTheoCIF", cifParameter);
        }
    
        public virtual ObjectResult<TraGocLai_Result> TraGocLai(Nullable<System.DateTime> ngaydl, Nullable<System.DateTime> ngaytragoctungay, Nullable<System.DateTime> ngaytragocdenngay)
        {
            var ngaydlParameter = ngaydl.HasValue ?
                new ObjectParameter("ngaydl", ngaydl) :
                new ObjectParameter("ngaydl", typeof(System.DateTime));
    
            var ngaytragoctungayParameter = ngaytragoctungay.HasValue ?
                new ObjectParameter("ngaytragoctungay", ngaytragoctungay) :
                new ObjectParameter("ngaytragoctungay", typeof(System.DateTime));
    
            var ngaytragocdenngayParameter = ngaytragocdenngay.HasValue ?
                new ObjectParameter("ngaytragocdenngay", ngaytragocdenngay) :
                new ObjectParameter("ngaytragocdenngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraGocLai_Result>("TraGocLai", ngaydlParameter, ngaytragoctungayParameter, ngaytragocdenngayParameter);
        }
    }
}
