//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLHIST_ERP
    {
        public System.DateTime DataDate { get; set; }
        public Nullable<System.DateTime> LMDATE { get; set; }
        public decimal BRANCH { get; set; }
        public decimal GTACCT { get; set; }
        public string TRDORC { get; set; }
        public decimal TRAMT { get; set; }
        public Nullable<decimal> TRDAT6 { get; set; }
        public Nullable<decimal> TREFF { get; set; }
        public string TRDESC { get; set; }
        public string TRCTYP { get; set; }
        public string TRCFYR { get; set; }
        public string TREFTH { get; set; }
        public string TRUSR2 { get; set; }
        public string TRUSRN { get; set; }
        public string TRAUXT { get; set; }
        public Nullable<decimal> TRSEQ { get; set; }
        public string TRTKTN { get; set; }
        public string TRSTAT { get; set; }
        public string trsys { get; set; }
        public string DEPTCODE { get; set; }
    }
}
