//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLMAST
    {
        public Nullable<System.DateTime> DataDate { get; set; }
        public Nullable<System.DateTime> LMDATE { get; set; }
        public decimal BRANCH { get; set; }
        public decimal ACCTGL { get; set; }
        public string GMCTYP { get; set; }
        public string GMCFYR { get; set; }
        public string TITLE { get; set; }
        public decimal CURBAL { get; set; }
        public decimal DRATDY { get; set; }
        public decimal CRATDY { get; set; }
        public decimal DRAWTD { get; set; }
        public decimal CRAWTD { get; set; }
        public decimal DRAMTD { get; set; }
        public decimal CRAMTD { get; set; }
        public decimal DRAQTD { get; set; }
        public decimal CRAQTD { get; set; }
        public decimal DRAYTD { get; set; }
        public decimal CRAYTD { get; set; }
        public decimal DECMEB { get; set; }
        public string ACTYPE { get; set; }
        public string ACTCAT { get; set; }
        public decimal CHGTDY { get; set; }
        public string NORBAL { get; set; }
    }
}
