//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLMAST_ERP
    {
        public System.DateTime DataDate { get; set; }
        public Nullable<System.DateTime> LMDATE { get; set; }
        public Nullable<decimal> BRANCH { get; set; }
        public decimal ACCTGL { get; set; }
        public string GMCTYP { get; set; }
        public string GMCFYR { get; set; }
        public string TITLE { get; set; }
        public Nullable<decimal> CURBAL { get; set; }
        public Nullable<decimal> DRATDY { get; set; }
        public Nullable<decimal> CRATDY { get; set; }
        public Nullable<decimal> DRAWTD { get; set; }
        public Nullable<decimal> CRAWTD { get; set; }
        public Nullable<decimal> DRAMTD { get; set; }
        public Nullable<decimal> CRAMTD { get; set; }
        public Nullable<decimal> DRAQTD { get; set; }
        public Nullable<decimal> CRAQTD { get; set; }
        public Nullable<decimal> DRAYTD { get; set; }
        public Nullable<decimal> CRAYTD { get; set; }
        public Nullable<decimal> DECMEB { get; set; }
        public string ACTYPE { get; set; }
        public string ACTCAT { get; set; }
        public Nullable<decimal> CHGTDY { get; set; }
        public string NORBAL { get; set; }
    }
}
