//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class LNDHIS_DATE
    {
        public string BRANCH { get; set; }
        public string ACCT_BRN { get; set; }
        public Nullable<System.DateTime> DATADATE { get; set; }
        public decimal LHACCT { get; set; }
        public string LHATYP { get; set; }
        public decimal LHTRAN { get; set; }
        public string LHDORC { get; set; }
        public string LHAFFT { get; set; }
        public string LHCUR { get; set; }
        public Nullable<decimal> LHAMT { get; set; }
        public Nullable<System.DateTime> LHEFD6 { get; set; }
        public Nullable<decimal> LHGRUP { get; set; }
        public Nullable<decimal> LHSEQN { get; set; }
        public string LHUSER { get; set; }
        public string LHAXTC { get; set; }
        public string LHPTYP { get; set; }
        public string LHOODS { get; set; }
        public string LHEFTH { get; set; }
        public string DEPTCODE { get; set; }
    }
}
