//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_checkdulieu
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datadate { get; set; }
        public Nullable<int> tbcount { get; set; }
        public string tablename { get; set; }
        public Nullable<int> thucte { get; set; }
    }
}
