//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_loaiKH
    {
        public string MaLoai { get; set; }
        public string TenMa { get; set; }
        public string TenTPKT { get; set; }
        public string Loai { get; set; }
    }
}
