//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ql_CIF
    {
        public int cif { get; set; }
        public string accno { get; set; }
        public string User_mo { get; set; }
        public string TenUserMo { get; set; }
        public string User_duyet { get; set; }
        public string TenUserDuyet { get; set; }
        public Nullable<System.DateTime> NgayMo { get; set; }
        public Nullable<System.DateTime> NgayDL { get; set; }
        public string TenKh { get; set; }
        public string noidungej { get; set; }
        public string curraccno { get; set; }
        public string IDNo { get; set; }
        public string EJSEQNO { get; set; }
        public string JRNLSEQNO { get; set; }
        public string dept_unhap { get; set; }
        public string dept_uduyet { get; set; }
    }
}
