//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPrinter
    {
        public string WorkStation { get; set; }
        public string printerService { get; set; }
    }
}
