//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsothe
    {
        public int id { get; set; }
        public string masothe { get; set; }
        public string Hoten { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<System.TimeSpan> gio { get; set; }
        public string trangthai { get; set; }
        public Nullable<int> branch { get; set; }
        public Nullable<System.DateTime> ngayadd { get; set; }
        public Nullable<System.DateTime> ngaybc { get; set; }
        public string LoaiThe { get; set; }
        public string DiaChi { get; set; }
        public string servicethe { get; set; }
        public string sotk { get; set; }
        public string cmnd { get; set; }
        public Nullable<System.DateTime> ngay802 { get; set; }
        public string usertacdong { get; set; }
        public Nullable<int> cif { get; set; }
    }
}
