//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbXoaATM
    {
        public string masothe { get; set; }
        public string Hoten { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string userxoa { get; set; }
        public string userduyet { get; set; }
        public System.DateTime ngaybc { get; set; }
        public Nullable<int> branch { get; set; }
        public string REMARKS1 { get; set; }
        public string REMARKS2 { get; set; }
        public Nullable<int> cif { get; set; }
    }
}
