//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insoden
{
    using System;
    using System.Collections.Generic;
    
    public partial class X1PCMS
    {
        public Nullable<System.DateTime> DATADATE { get; set; }
        public string BRANCH { get; set; }
        public Nullable<System.DateTime> LASTMDATE { get; set; }
        public decimal ISD { get; set; }
        public decimal ISM { get; set; }
        public decimal ISY { get; set; }
        public string CARDD { get; set; }
        public string AC1 { get; set; }
        public string AC2 { get; set; }
        public string AC3 { get; set; }
        public string SHRTNM { get; set; }
        public string CUID { get; set; }
        public string TYP { get; set; }
        public string AD1 { get; set; }
        public string AD2 { get; set; }
        public string OPER { get; set; }
        public Nullable<System.DateTime> LMDATE { get; set; }
        public string DELC { get; set; }
        public string LGLID { get; set; }
        public string CDSTAT { get; set; }
        public string AD3 { get; set; }
        public string AD4 { get; set; }
    }
}
